# 프로젝트 설정 파일
project:
  name: "대규모 상담/게시판 데이터 주제 발견 및 심층 분석"
  version: "1.0.0"

# 데이터 설정
data:
  input_file: "data_sample.xlsx"
  output_dir: "outputs"
  columns:
    id: "연번"
    date: "상담일자"
    type: "상담유형"
    summary: "상담요약"
    person_type: "상담인 유형"
    content: "상담내용"
  
# 전처리 설정
preprocessing:
  min_text_length: 20
  remove_duplicates: true
  text_columns: ["상담요약", "상담내용"]
  
# 주제 발견 설정
topic_discovery:
  algorithm: "lda"  # lda, nmf, bertopic
  n_topics: 3
  min_df: 1
  max_df: 0.9
  top_terms_per_topic: 10
  auto_find_topics: true  # 최적 주제 수 자동 탐색
  
  # 대용량 데이터 처리 설정
  large_scale:
    enabled: false  # 대용량 데이터 처리 모드 (true로 설정하면 활성화)
    sample_size: 1000  # 샘플링 크기 (전체 데이터가 이보다 크면 샘플링)
    max_topics_search: 10  # 최적 주제 수 탐색 범위 제한
    use_keyword_naming: true  # LLM 대신 키워드 기반 주제명 생성
    batch_size: 1000  # 배치 처리 크기
    memory_efficient: true  # 메모리 효율적 처리
  
# 클러스터링 설정
clustering:
  algorithm: "kmeans"
  n_clusters_range: [5, 15]
  embedding_model: "paraphrase-multilingual-MiniLM-L12-v2"
  
# LLM 설정
llm:
  model: "gpt-3.5-turbo"
  max_tokens: 1000
  temperature: 0.1
  
# 출력 설정
output:
  csv_files:
    - "global_topics_top_terms.csv"
    - "topic_assignments.csv"
    - "cluster_summary.csv"
  report_format: ["markdown", "pdf"]
  visualizations:
    - "topic_distribution.png"
    - "wordclouds/"
    - "frequency_charts/" 